# Generated by Django 3.0.7 on 2020-06-16 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getawayHolidays', '0002_accommodations_activities_activityschedule_employees_masseuse_outdoorinstructors_rooms_swimminginstr'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_rooms', models.IntegerField(default=1)),
                ('connecting_rooms', models.BooleanField(default=False)),
                ('client_signature', models.CharField(max_length=255)),
                ('signature_date', models.DateTimeField()),
                ('agent_signature', models.CharField(max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('accommodations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getawayHolidays.Accommodations')),
                ('activities', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='getawayHolidays.Activities')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=10, null=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=255, null=True)),
                ('marital_status', models.CharField(choices=[(0, 'single'), (1, 'married')], max_length=24)),
                ('spouse', models.CharField(max_length=255, null=True)),
                ('anniversary', models.DateTimeField()),
                ('gender', models.CharField(choices=[(0, 'Male'), (1, 'Female')], max_length=24)),
                ('city', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('client_signature', models.CharField(max_length=255)),
                ('signature_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('health_conditions', models.ManyToManyField(null=True, to='getawayHolidays.HealthConditions')),
            ],
        ),
        migrations.AddField(
            model_name='activities',
            name='restrict_conditions',
            field=models.ManyToManyField(null=True, to='getawayHolidays.HealthConditions'),
        ),
    ]
