# Generated by Django 3.0.7 on 2020-06-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getawayHolidays', '0006_auto_20200617_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsprofile',
            name='anniversary',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientsprofile',
            name='health_conditions',
            field=models.ManyToManyField(blank=True, null=True, to='getawayHolidays.HealthConditions'),
        ),
        migrations.AlterField(
            model_name='clientsprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientsprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientsprofile',
            name='spouse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
