# Generated by Django 3.0.7 on 2020-06-23 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('getawayHolidays', '0007_auto_20200617_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='client_id',
        ),
        migrations.AddField(
            model_name='reservations',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
