# Generated by Django 3.0.7 on 2020-06-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getawayHolidays', '0008_auto_20200623_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='activity_type',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=24),
        ),
        migrations.AlterField(
            model_name='activities',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='risk_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=24),
        ),
    ]
