# Generated by Django 3.0.7 on 2020-06-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getawayHolidays', '0010_auto_20200623_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='agent_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
