# Generated by Django 3.0.7 on 2020-06-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getawayHolidays', '0012_auto_20200623_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
