# Generated by Django 3.0.7 on 2020-06-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getawayHolidays', '0013_reservations_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='duration',
        ),
    ]
