# Generated by Django 3.0.7 on 2020-06-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getawayHolidays', '0014_remove_reservations_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
